spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://127.0.0.1:5432/nbu-project
    hikari:
      schema: nbu-project
    password: qwe0zPostgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
#      ddl-auto: create
    show-sql: 'true'
  flyway:
    schemas: nbu-project
    url: jdbc:postgresql://127.0.0.1:5432/nbu-project
    user: postgres
    password: qwe0zPostgres

taxConfig:

